{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "duke.serviceAccountName" . }}
  labels:
{{ include "duke.labels" . | nindent 4 }}
{{- end -}}
